graph TD
AA[1914<br/>Thomas Watson leaves NCR and becomes president of CTR]
AA --> A
A[1944<br/>IBM ASCC / Harvard Mark I]
B[1947<br/>Harvard Mark II]
C[1948<br/>IBM SSEC]
A --> B
A -->|IBM thinks Aiken takes too much credit|C
C --> D
D[1952<br/>IBM 70x series]
